# Generated by Django 3.0.6 on 2020-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VK_getter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True, max_length=100)),
                ('messages', models.TextField(blank=True, max_length=500)),
                ('messages_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VK_Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True, max_length=100)),
                ('messages', models.TextField(blank=True, max_length=500)),
                ('messages_count', models.IntegerField()),
            ],
        ),
    ]
