# Generated by Django 3.0.6 on 2020-06-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VK_getter',
        ),
    ]
