# Generated by Django 3.0.6 on 2020-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_bot', '0003_auto_20200602_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vk_sender',
            name='meet_location_x',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vk_sender',
            name='meet_location_y',
            field=models.TextField(blank=True),
        ),
    ]
