# Generated by Django 3.0.6 on 2020-06-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_bot', '0004_auto_20200602_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vk_sender',
            name='key',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
