# Generated by Django 3.0.6 on 2020-06-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_bot', '0007_vk_sender_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vk_sender',
            old_name='message',
            new_name='text',
        ),
        migrations.AddField(
            model_name='vk_sender',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
