# Generated by Django 3.0.6 on 2020-06-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_bot', '0008_auto_20200604_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='vk_sender',
            name='key_phrase',
            field=models.TextField(blank=True),
        ),
    ]
