# Generated by Django 3.0.6 on 2020-06-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_bot', '0009_vk_sender_key_phrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vk_sender',
            old_name='meet_location_x',
            new_name='coor_x',
        ),
        migrations.RenameField(
            model_name='vk_sender',
            old_name='meet_location_y',
            new_name='coor_y',
        ),
    ]
